### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by cristiandonosoc** [Extrawurst/cimgui#17]
This is not really an issue, but me not knowing exactly how to use the C-wrapper. A noob issue.
I get that you compile the project using a C++ compiler and you export the functions to C and link against them.
The problem I have is using the types. cimgui.h only has forward-declarations, so I cannot set inner properties of ImGuiIO.
I looked at your D-binding and you have a header that defines the types to be used.
Do I need to do that here? If so, I wonder why that header is not already included. I feel that I am missing something.

Thanks!

**Comment by MusorGaming** [comment]
It's not so much a noob issue, as the wrapper is well..... uh... lazy (to say the least).
It literally doesn't do almost anything, but wrap the C++ calls.

The struct's don't get exposed anywhere. Luckily most of the relevant Imgui structs are very close to C (or direct C) so you can pull them out of imgui.h and put it in your C code.

What I did is - I did all the tinkering with ImGuiIO state in the C++ side of things, along with the wrapper. The opengl_example included with imgui is actually very handy. (imgui_impl_glfw.cpp and imgui_impl_glfw.h). This comes along with C-ish interface. I basically added imgui_impl_glfw.cpp to cimgui project and exported those functions as C functions and call them from my C project, and it kind-of works, since I dont need to access almost any imgui structs from C code anymore.

**Comment by sonoro1234** [comment]
How for example you would access from C to the member Framerate of the struct returned by igGetIO()

**Comment by sevas** [comment]
@sonoro1234:

I settled on re-interpreting what's behind the pointer using the native compound-type declaration of the target language. 
For C, I would simply re-declare a struct that mimics the contents of the [ImguiIO c++ struct](https://github.com/ocornut/imgui/blob/adb85d800d70d3ddc4548f0e8f184eede4568034/imgui.h#L732-L839), keep only the data fields, replace things like ``ImVec2`` with (for instance) ``cImVec2`` struct that have the same amount of contents in bytes. It's a bit tedious, and will clearly break the day imgui decides to change something in there. But it's simple.

I'm making a python wrapper that goes through cimgui, and I use cffi to reinterpret what's behind the ``ImguiIO``, ``ImDrawData``, ``ImDrawCmd`` pointers returned by cimgui. I think it makes sense from cimgui's point of view to not bother too much with that. If it were to provide wrapped C structs, a binding library would need to do this sort of conversion/marshalling to native types anyway.

This is similar to what the authors of cimgui do in their [D wrapper for imgui](https://github.com/Extrawurst/DerelictImgui/blob/master/source/derelict/imgui/types.d#L291-L414)

**Comment by sonoro1234** [comment]
@sevas 
the dangerous part seems to expect a specific packing from the C++ compiler, also dangerous seems the fact that some compilers set a this pointer in the structure

see: http://lua-users.org/lists/lua-l/2011-07/msg00528.html

**Comment by sevas** [comment]
For the packing, sure, it could happen.
Regarding the ``this`` pointer, it should happen only if the struct/class has virtual members. Imgui structs, AFAICT, do not.

It's still possible to add a proper C API on top of the data types, if you find it too risky to rely on ABI compatibility. But then this would need to be merged with upstream cimgui, or fork the project if this is out of the scope intended by the authors (I have no idea if it is or not, I'm just another cimgui user.)

**Comment by sonoro1234** [comment]
Thanks for your guidance, now I will have to experiment a bit.

**Comment by Extrawurst** [comment]
back to the original question @cristiandonosoc these heasders are now inclued
